services:
  postgres:
    image: postgres:16-alpine
    container_name: pfm_dev_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: pfm_dev
      POSTGRES_USER: pfm_user
      POSTGRES_PASSWORD: secret_password
    volumes:
      - pfm_postgres_data:/var/lib/postgresql/data

volumes:
  pfm_postgres_data:
